username: reid.wynkoop8@gmail.com
password: Sharknado7

positions:
- Software Engineer
#- #back end developer
#- #backend developer

locations:
- Remote

# --------- Optional Parameters -------
#uploads:
Resume: C:\Users\wynko\Dropbox\Reid_Wynkoop_Resume.pdf
#  Cover Letter: # PATH TO cover letter
#  Photo: # PATH TO photo

# output_filename:
# - # PATH TO OUTPUT FILE (default output.csv)

blacklist:
- Walmart
- Walmart Global Tech
- Insight Global
- SRC, Inc
- Amazon
- Google
- Microsoft
- Capital One
- Confidential
# - # Company names you want to ignore

#blackListTitles:
#- # Add job titles you want to ignore